### PR TITLE
Golang challenge updates

### PR DESCRIPTION
**Pull request by kplakidas**
Time to update the challenge a bit:

- update Go version to 1.20
- some hopefully clarifying tweaks to task description based on our experience with candidates' submissions
- make GET operations mandatory

### CODE REVIEW

**Review by ppaulweber — DISMISSED** [review]
LGTM :+1: Maybe we could force the challenger to implement retrieval and representation GET endpoints of the information as well, hat do you think @kplakidas?

**Comment by kplakidas** [comment]
@ppaulweber might be a good idea to force people to deal with sensible RESTful naming, correct HTTP verbs, etc. Will add to the README

**Review by ppaulweber — APPROVED** [review]
LGTM :+1:

**Comment by auxdevelopment** [comment]
> LGTM +1 Maybe we could force the challenger to implement retrieval and representation GET endpoints of the information as well, what do you think @kplakidas?

Not having to implement the retrieval functions was a conscious choice because from my point of view it does not add any insights for us and causes (unnecessary) effort for the interviewee. The goal should be to minimize the effort required on their side while maximizing the insights we can get about the candidate. I would keep them out.

**Comment by kplakidas** [comment]
@auxdevelopment the concern is that we increasingly see minimal solutions, with a very basic domain model and poor API design in terms of naming, extensibility, etc.
There is an argument to be made that this allows us to quickly fail people,but I am not so sure. I feel,just as with students,that if you ask for a minimal solution, that's what you will get. I.e. if we want to see what they can do,we should ask for it.

**Comment by kplakidas** [comment]
@ppaulweber I need at least one more approval before merging.

**Pull request merged**
